### ISSUE TITLE
Protocol Version 5

### ISSUE THREAD

**Issue by tanwarsatya** [vernemq/docker-vernemq#163]
To enable MQTT 5.0 document says we need to specify 

> listener.tcp.allowed_protocol_versions = 3,4,5

> https://vernemq.com/intro/mqtt-primer/mqtt5_getting_started.html

I am not able to find a way to specify the same with helm charts.

**Comment by larshesel** [comment]
I belive you need to set the appropriate environment variable as documented in the VerneMQ configuration: https://github.com/vernemq/docker-vernemq#vernemq-configuration

For Helm that would then be via the helm chart similar to this: https://github.com/vernemq/docker-vernemq/blob/master/helm/vernemq/README.md#set-the-environment-variables-for-the-ssl-listener

Hope this helps

**Comment by tanwarsatya** [comment]
Thanks I was able to resolve it with env variables as you have mentioned.

**Comment by cedricve** [comment]
@tanwarsatya wwhat is the environment variables you used?

**Comment by Chadys** [comment]
Probably too late for @cedricve , but since I was looking into resolving the following:
`[warning] invalid protocol version for {[],undefined} 5`
and got to this post in the process where I learnt that v5 is not enabled by default, and since I hate it when OP goes "oh cool I resolved my problem", without telling the community exactly HOW, here is the explicit variable you need to set:
```yaml
    environment:
      DOCKER_VERNEMQ_LISTENER.tcp.allowed_protocol_versions: 3,4,5
```
(written in a docker-compose file, use method you want to set the environment variables)
As a rule of thumb, to set a VerneMQ docker variable, take the corresponding config variable, prefix it with `DOCKER_VERNEMQ_` and uppercase it. If the variable contains a ".", everything after the first dot need to stay lowercase.
Hope it help some people.
