### ISSUE TITLE
some regular questions...

### ISSUE THREAD

**Issue by cissusnar** [vernemq/docker-vernemq#358]
mount /vernemq/etc cause some issues, like `can't find vm.args`. 
mount /vernemq/data will failed run docker instance too. 

why I can't mount these dirs?

**Comment by ioolkos** [comment]
@cissusnar what image are you using exactly?
How do you configure and run it? I'm just asking for more context, basically.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by cissusnar** [comment]
```bash
#!/usr/bin/env bash

args=(
	run
	--rm
	-p 1883:1883
	-p 8888:8888
	-e "DOCKER_VERNEMQ_ACCEPT_EULA=yes"
#	--restart always
	-v /home/vernemq/etc:/vernemq/etc
	-v /home/vernemq/data:/vernemq/data
#        --mount type=tmpfs,dst=/vernemq/data
	--name vernemq
#	-d
	-it
	vernemq/vernemq:latest-alpine
#	vernemq/vernemq:latest
	/bin/bash
)

docker "${args[@]}"
```
this is my launch script. 
I tried latest-alpine and latest, all have same problem, may be the environment variables cause the problem? 

``` console
# ls /home/vernemq/etc
vernemq.conf  vernemq.conf.dpkg-dist  vm.args  vm.args.bak  vmq.acl  vmq.passwd
```
`vm.args` is copy from docker image, I can't run the docker image without vm.args in /etc, but I can run native vernemq on host without it.

**Comment by ioolkos** [comment]
@cissusnar There's a difference in how Linux packages and Docker images handle the `vm.args` file. In the Linux packages, the file is optional (to manually override the full set of Erlang VM settings). In Docker, the `vm.args` file is needed, since we use it to inject settings. This is done via script:
https://github.com/vernemq/docker-vernemq/blob/master/bin/vernemq.sh

Mounting of `etc` and `data` should in principle work. Maybe you try to mount existing data and settings from a previous local Linux install? This might not work due to settings like nodename or cluster state.

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.

**Comment by cissusnar** [comment]
@ioolkos 
thanks for reply. 
the vm.args is not the problem now. 
but still can't launch with mount /vernemq/data, I tried mount with tmpfs, `--mount type=tmpfs,dst=/vernemq/data`. 
```bash
#!/usr/bin/env bash
args=(
	run
	--rm
	-p 1883:1883
	-p 8888:8888
	-e "DOCKER_VERNEMQ_ACCEPT_EULA=yes"
#	--restart always
#	-v /home/webuser/vernemq:/vernemq/etc
	--mount type=tmpfs,dst=/vernemq/data
	--name vernemq
#	-d
	-i
	vernemq/vernemq:latest-alpine
#	/bin/bash
)

docker "${args[@]}"
```

same error out: 
```console
Error generating config with cuttlefish
  run `vernemq config generate -l debug` for more information.
```
test on gentoo and debian host.

**Comment by cissusnar** [comment]
I check the error with `vernemq config generate -l debug`, it's a `permission` problem, I can fix it by myself.
