### ISSUE TITLE
Error joining a node on different host in a cluster

### ISSUE THREAD

**Issue by vinaynb** [vernemq/docker-vernemq#65]
Hello,

I have two hosts A & B and both are connected to local LAN 

I started a container on host A with following command
```bash
docker run -e "DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on" --name vernemq1 -p 1883:1883 -p 8883:8883 -d erlio/docker-vernemq
```
Now i start a container on host B with below command
```bash
docker run -e "DOCKER_VERNEMQ_DISCOVERY_NODE=192.168.1.33" --name vernemq2 -d erlio/docker-vernemq
````
where 192.168.1.33 is A's local ip address

when i run `sudo docker exec vernemq1 vmq-admin cluster show` it shows just a single node in cluster.

I tailed logs of container running on B and it shows error connecting to cluster as shown below.
`
12:36:19.159 [info] cluster event handler 'vmq_cluster' registered
12:36:19.801 [info] Application vmq_acl started on node 'VerneMQ@172.17.0.3'
12:36:19.865 [info] Application vmq_passwd started on node 'VerneMQ@172.17.0.3'
12:36:19.922 [info] Application vmq_server started on node 'VerneMQ@172.17.0.3'
12:36:19.946 [info] Sent join request to: 'VerneMQ@192.168.1.33'
12:36:19.950 [info] Unable to connect to 'VerneMQ@192.168.1.33'
`
Ironically when running the above two containers locally they are able to join and form a cluster.

looks like a docker networking issue but i cannot figure it out exactly what's blocking two nodes from communicating. Any help ?

**Comment by dergraf** [comment]
Hello @vinaynb, thank you for your patience!
Instead of the Host IP Address, you should be using the containers IP address, you'll figure it out using

`docker inspect vernemq1 |grep "IPAddress"` on Host A.

Of course clustering will only work if the networking is properly setup between those hosts and Docker, which is out of scope of VerneMQ. My recommendation is to use something like Kubernetes or Swarm to do multi host containerized deployments.
