### ISSUE TITLE
Suggested kubernetes deployment

### ISSUE THREAD

**Issue by cbluth** [vernemq/docker-vernemq#79]
I am having issues getting vernemq to cluster with the docker image on kubernetes.
Here is the manifest that I am using: https://gist.github.com/cbluth/f77b658e09781ef36f1ba317b41e1a31#file-vernemq-statefulset-dev-yaml

Can someone validate that manifest as working, or point out improvements?
Or does someone have their own suggested manifest?

**Comment by kag0** [comment]
I'm having this same issue. I see things around online using stateful sets, but it's not clear to me why a deployment wouldn't work.   
Could we add a minimal yaml or link to one in the readme?

**Comment by kag0** [comment]
That is helpful, thanks!

I have a few questions though (some might seem silly because I'm a kubenoob)

1. Is the `mqtt` service necessary for use cases that don't require external access directly to the nodes? If it is necessary to have that service, could it be changed to a `ClusterIP` service? (in my specific use case I'd put TLS termination on the LB service and have no external access directly to the nodes)
2. How/where are the service account/rbac parts used? Are they also strictly needed?
3. Is this redundant?
``` 
- containerPort: 1883
  name: mqttlb
- containerPort: 1883
  name: mqtt
```
4. Less of a question and more of a suggestion; pretty much all the ports that aren't 1883 feel somewhat unexpected. In the [documentation for joining a non-kube docker cluster](https://docs.vernemq.com/installing-vernemq/docker) it seems like 1883 is all that's required and a casual reader wouldn't expect that a port for epmd is needed unless they wandered all the way to the [page for inter-node communication](https://docs.vernemq.com/vernemq-clustering/communication) where we become aware that we might need a whole port range. So the suggestion would be to either elaborate more on the docker clustering page, or link to the inter-node communication page (or both).

**Comment by francois-travais** [comment]
I suggest to take a look at the [Helm chart](https://github.com/vernemq/docker-vernemq/tree/master/helm/vernemq)

**Comment by TammeThijs** [comment]
While the configuration posted above seems to be working fine, using the helm chart leaves me with the following error message: `Node 'VerneMQ@vernemq-0.default.svc.cluster.local' not responding to pings.`

I looks like its missing ".vernemq" when trying to ping?

**Comment by francois-travais** [comment]
@TammeThijs Which version of the docker image are you using? Is it `latest`? There has been PR merged recently which may fix your problem.

**Comment by TammeThijs** [comment]
I was using `1.6.2-2-gbea60e3`, as specified in the helm chart. Switched to latest which seems to be working fine!
